test with dead relay
relaystr/ndk pull request #80
Opened 2024-12-21 09:36 UTC by leo-lox

2024-12-22 11:59 UTC, leo-lox commented
the out controller is no longer closed in relay manager. 
Instead its in requests and relay manager closes the network stream `_checkNetworkClose()`
Not ideal because we need to check if the relay is still online.

Also changed the DEFAULT_WEB SOCKET_CONNECT_TIMEOUT to 4s so ndk startup is fast enough even if some relays are down

2024-12-23 08:54 UTC, frnandu commented
Important and much needed tests, nice job!

2024-12-23 09:04 UTC, frnandu approved these changes

2024-12-29 13:20 UTC, frnandu requested changes

2024-12-29 13:20 UTC, frnandu commented on packages/ndk/lib/presentation_layer/init.dart
> -          signer: _ndkConfig.eventSigner,
We need to pass this for the nip-42 auth to sign the challenge.
`_ndkConfig.eventSigner` is optional anyways.

2024-12-30 00:11 UTC, merged